options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/recipiz-457601/raw-text-extractor', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/recipiz-457601/raw-text-extractor']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'raw-text-extractor',
        '--image', 'gcr.io/recipiz-457601/raw-text-extractor',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/recipiz-457601/raw-text-extractor
