options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/recipiz-457601/raw-text-extractor-repo/raw-text-extractor', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/recipiz-457601/raw-text-extractor-repo/raw-text-extractor']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    [
      'run', 'deploy', 'raw-text-extractor',
      '--image', 'us-central1-docker.pkg.dev/recipiz-457601/raw-text-extractor-repo/raw-text-extractor',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - us-central1-docker.pkg.dev/recipiz-457601/raw-text-extractor-repo/raw-text-extractor
